# Parameters necessary for data creation from zero

# Necessary pathes to geometry manipulations
# save_storage: './test_data/geometry/example_ws'
# watershed_name : 'test_builder'
# acc_faktor: 1000
# point_geometry: './test_data/geometry/example_gauges.gpkg'

# mask_storage: './test_data/geometry_builder/region_masks'
# accum_masks: './test_data/geometry_builder/accum_masks'
# raster_storage: './test_data/geometry_builder/aoi_rasters'
# initial_fdir: './test_data/geometry_builder'

# watershed_storage: './test_data/geometry/example_ws/res'
# river_net_storage: './test_data/geometry/river_network'
# # Necessary pathes for meteo aggregationsfinal
# grid_storage: './test_data/meteo_grids'
# final_meteo: './test_data/xr_meteo'

# # Necessary pathes to geometry manipulations
# inside container ../ outside /home/dima/Data
watershed_storage: '/home/dima/Data/geo_data/great_db/geometry/'
watershed_name : 'russia_ws'
grid_storage: '/home/dima/Data/geo_data/cmip_result_585'
save_storage: '/home/dima/Data/geo_data/great_db/geometry/example_ws'

acc_faktor: 1000
point_geometry: '/home/dima/Data/geo_data/great_db/geometry/russia_gauges.gpkg'

mask_storage: '/home/dima/Data/geo_data/great_db/geometry_builder/region_masks'
accum_masks: '/home/dima/Data/geo_data/great_db/geometry_builder/accum_masks'
raster_storage: '/home/dima/Data/geo_data/great_db/geometry_builder/aoi_rasters'
initial_fdir: '/home/dima/Data/geo_data/great_db/geometry_builder'

river_net_storage: '/home/dima/Data/geo_data/great_db/geometry/river_network'
# Necessary pathes for meteo aggregations
initial_meteo: '/home/dima/Data/geo_data/meteorology'
final_meteo: 

#Parameters for ML model
ml_posts_path: 
ais_first_date: '01-01-2008'
ais_last_date: '12-31-2017'
forecast_predictors:
forecast_start_date: '01-01-2018'
forecast_end_date: '12-31-2020'  # max 12-31-2019
roc_auc_year: '2018'

#Common parameters
ws_path: 
layers_path: 
id_label_path: 
cmip_path: 
meteo_path: 
features_path: 

water_cons_path: 
water_lvl_path: 

elevations_path: 
results_path: 
dzz_path: 
mask_type: 
sat_images_path: 
max_distance_to_post_km: 