additional_feature_files: None
batch_size: 256
cache_validation_data: true
checkpoint_path: None
clip_gradient_norm: 1
data_dir: ../geo_data
dataset: generic
device: cuda:0
dynamic_inputs:
- prcp_mswep
- t_max_e5l
- t_min_e5l
dynamics_embedding:
epochs: 30
evolving_attributes:
experiment_name: cudalstm_q_mm_day_256_10_mswep_static
forecast_hidden_size:
forecast_overlap:
head: regression
hidden_size: 256
hindcast_hidden_size:
initial_forget_bias: 6
learning_rate:
  0: 0.001
  10: 0.0005
  20: 0.0001
log_interval: 2
log_n_figures:
log_tensorboard: false
loss: NSE
metrics:
- NSE
- RMSE
- KGE
model: cudalstm
num_workers: 8
optimizer: Adam
output_activation: linear
output_dropout: 0.4
per_basin_test_periods_file: None
per_basin_train_periods_file: None
per_basin_validation_periods_file: None
predict_last_n: 1
regularization:
run_dir: model_runs
save_train_data: true
save_validation_results: true
save_weights_every: 1
seed: 42
seq_length: 10
state_handoff_network:
static_attributes:
- for_pc_sse
- crp_pc_sse
- inu_pc_ult
- ire_pc_sse
- lka_pc_use
- prm_pc_sse
- pst_pc_sse
- cly_pc_sav
- slt_pc_sav
- snd_pc_sav
- kar_pc_sse
- urb_pc_sse
- gwt_cm_sav
- lkv_mc_usu
- rev_mc_usu
- ws_area
- ele_mt_sav
statics_embedding:
target_noise_std: 0.005
target_variables:
- q_mm_day
test_basin_file: every_basin.txt
test_end_date: 31/12/2020
test_start_date: 01/01/2019
train_basin_file: every_basin.txt
train_data_file: None
train_end_date: 31/12/2016
train_start_date: 01/01/2008
use_basin_id_encoding: false
validate_every: 1
validate_n_random_basins: 1111
validation_basin_file: every_basin.txt
validation_end_date: 31/12/2018
validation_start_date: 01/01/2017
