# Single Gauge TFT Configuration
# Configuration for training TFT model on individual gauges

data:
  meteo_input:
    - "prcp_e5l"
    - "t_max_e5l" 
    - "t_min_e5l"
  hydro_target: "q_mm_day"  # or "lvl_sm" for water level
  index_col: "gauge_id"

model:
  input_chunk_length: 90
  output_chunk_length: 30
  hidden_size: 64
  lstm_layers: 2
  num_attention_heads: 4
  dropout: 0.1
  batch_size: 16
  n_epochs: 50
  lr: 0.001
  random_state: 42
  likelihood: "quantile"
  quantiles:
    - 0.01
    - 0.05
    - 0.1
    - 0.25
    - 0.5
    - 0.75
    - 0.9
    - 0.95
    - 0.99

training:
  train_split: 0.7
  val_split: 0.2
  test_split: 0.1
  early_stopping_patience: 15
  save_checkpoints: true

paths:
  data_root: "../geo_data"
  ws_geometry_file: "../geo_data/geometry/russia_ws.gpkg"
  static_attributes_file: "../geo_data/attributes/static_with_height.csv"
  nc_data_pattern: "../geo_data/ws_related_meteo/{nc_variable}/*.nc"
  output_dir: "outputs"
  model_dir: "models"
